In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Import Necessary Librabries

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [10]:
#Loading Titanic Data
file_path = '/content/drive//MyDrive/ML/LAB/titanic.csv'
df = pd.read_csv(file_path)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [18]:
#Dropping Irrelevant Columns
df = df.drop(['PassengerId','Name','Ticket','Cabin'],axis=1, errors='ignore')
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [20]:
#Handling Missing Values
imputer = SimpleImputer(strategy='most_frequent')
df['Age'] = imputer.fit_transform(df[['Age']]).ravel()
df['Embarked'] = imputer.fit_transform(df[['Embarked']]).ravel()
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [21]:
#Encoding Categorical Variables
label_encoder = LabelEncoder() #label encoding Object
df['Sex'] = label_encoder.fit_transform(df['Sex'])  # 1 = male and 0 = female (labelling and mapping using Fit_Transform)
df['Embarked'] = label_encoder.fit_transform(df['Embarked'])
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [23]:
#Splitting data into features and target
X = df.drop('Survived', axis=1)
y = df['Survived']

In [24]:
#Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X , y, test_size=0.2, random_state=42)

In [25]:
#Standardizing Features
scaler = StandardScaler()  # object of standardscalar
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [44]:
#initializing logistic regression model
l_reg_model = LogisticRegression()

#Training the model
l_reg_model.fit(X_train_scaled, y_train)
#Predictions
y_pred = l_reg_model.predict(X_test_scaled)

#evaluating the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.7988826815642458

Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.86      0.83       105
           1       0.78      0.72      0.75        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179


Confusion Matrix:
[[90 15]
 [21 53]]

In [43]:
# Now using this with SVM
from sklearn.svm import SVC

#initializing svm model
svm_model = SVC()

#Training the model
svm_model.fit(X_train_scaled, y_train)

#Predictions
y_pred = svm_model.predict(X_test_scaled)

#evaluating the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8156424581005587

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.89      0.85       105
           1       0.82      0.72      0.76        74

    accuracy                           0.82       179
   macro avg       0.82      0.80      0.81       179
weighted avg       0.82      0.82      0.81       179


Confusion Matrix:
[[93 12]
 [21 53]]